# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 274b3da1cb9552b691ee12532f5ad405b4f03b64135d3fc3bc2f63c0f729d0826b9149da19da7480b5d03d09df64ea31a47cac594e1649cb0931b3a7af52ad5f

test:
  secret_key_base: 91e0962107b9619f09c145bbdc400022cdaf3875a792aa98e656740437d9198979822d84764f2d7d8e9abe78c946c622c29ab2bbde65cc7159923b75f90e5ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
